refactor: command sync
Pycord-Development/pycord-v3 pull request #112
Opened 2022-12-26 04:18 UTC by VincentRPS

## Summary

This PR refactors and moves the previous logic of `ApplicationCommand.instantiate` to `state.sync_command` to make command syncing and parsing easier.

I have not tested this yet.

## Checklist

- [x] This PR has breaking changes
- [ ] This PR fixes an issue
- [ ] This is **not** a code change
- [ ] If code changes were made they have been tested
- [ ] I have properly changed the docs to appeal to this change

2022-12-26 04:40 UTC, EmreTech requested changes
I can tell that you also ran formatting tools (black, isort, whatever else you're using) with this PR and it affected files that aren't relevant to this PR.

2022-12-26 04:40 UTC, EmreTech commented on pycord/state/core.py
> +                    tasks.extend(self._process_global_command_for(command))
You have to actually run the async function to get the list of coroutines.

2022-12-26 04:40 UTC, EmreTech commented on pycord/state/core.py
> +            t.append(self._process_global_command(app_command, command))
But `app_command` isn't application command data... it's an application command object.

2022-12-26 04:40 UTC, EmreTech commented on pycord/state/core.py
> +    async def _process_global_command_for(self, command: Command) -> list[Coroutine]:
Why is `command` type hinted as `Command` if this is for application commands?

2022-12-26 04:40 UTC, EmreTech commented on pycord/state/core.py
> +                    if created is True:
Why use `is True`? `created` is just a bool, so `if created` will work just fine.

2022-12-26 04:40 UTC, EmreTech commented on pycord/state/core.py
> +            )
This formatting is hurting my eyes.

2022-12-26 04:40 UTC, EmreTech commented on pycord/state/core.py
> +            for app_cmd in guild_commands:
I'm confused about this logic. Why is it looping through every application command found in a guild and performing operations on those application commands? Aren't we supposed to focus on the one application command this function was provided?

2022-12-26 04:40 UTC, EmreTech commented on pycord/state/core.py
> +            self.id = app_cmd['id']
```suggestion
            command.id = app_cmd['id']
```

2022-12-26 04:40 UTC, EmreTech commented on pycord/state/core.py
> +            return
This is done anyways? If the if statement this else statement is connected to evaluates to `False`, then `created` is still `False` so the code below doesn't execute.

2022-12-26 04:40 UTC, EmreTech commented on pycord/state/core.py
> +                    command.id = app_cmd['id']
But what if this command is rolled out to multiple guilds? Then it has multiple ids for each guild.

2022-12-27 04:18 UTC, baronkobama requested changes
Altogether, the entirety of my review is reverting the out of scope changes made. While most of these changes should be made, let's put them in a separate formatting/code cleanup PR.

2022-12-27 04:18 UTC, baronkobama commented on examples/interactions/commands/application_commands.py
> +
Reverts out of scope change.
```suggestion
    
```

2022-12-27 04:18 UTC, baronkobama commented on examples/interactions/commands/application_commands.py
> +        case 'Attack on Titan':
Reverts out of scope change.
```suggestion
        case "Attack on Titan":
```

2022-12-27 04:18 UTC, baronkobama commented on examples/interactions/commands/application_commands.py
> +            )
Reverts out of scope change.
```suggestion
            await inter.resp.send("おにいちゃんありがとう. You like JoJo's Bizzare Adventure. Nice!")
```

2022-12-27 04:18 UTC, baronkobama commented on examples/interactions/commands/application_commands.py
> +                'I have a friend which really likes this anime, '
Reverts out of scope change.
```suggestion
                "I have a friend which really likes this anime, "
```

2022-12-27 04:18 UTC, baronkobama commented on pycord/ext/gears/gear.py
> +
Reverts out of scope change.
```suggestion
```

2022-12-27 04:18 UTC, baronkobama commented on pycord/ext/gears/gear.py
> +ContextT = TypeVar('ContextT', bound=BaseContext)
Reverts out of scope change.
```suggestion
ContextT = TypeVar('ContextT', bound=BaseContext)
```

2022-12-27 04:18 UTC, baronkobama commented on pycord/ext/gears/gear.py
> +
Reverts out of scope change.
```suggestion
```

2022-12-27 04:18 UTC, baronkobama commented on pycord/ext/gears/gear.py
> +from typing import TYPE_CHECKING, Any, Generic, Type, TypeVar
Reverts out of scope change.
```suggestion
from typing import TYPE_CHECKING, Any, Generic, Type, TypeVar
```

2022-12-27 04:18 UTC, baronkobama commented on pycord/ext/gears/gear.py
Reverts out of scope change.
```suggestion
from types import SimpleNamespace

```

2022-12-27 04:18 UTC, baronkobama commented on pycord/interaction.py
> +from .flags import MessageFlags
Reverts out of scope change.
```suggestion
from .flags import MessageFlags

from .embed import Embed
from .errors import InteractionException
```

2022-12-27 04:18 UTC, baronkobama commented on pycord/interaction.py
> +from .flags import MessageFlags
Reverts out of scope change.
```suggestion
from .flags import MessageFlags

from .embed import Embed
from .errors import InteractionException
```

2022-12-27 04:18 UTC, baronkobama commented on pycord/ui/house.py
> +            )
Reverts out of scope change.
```suggestion
            raise ComponentException('Cannot add more components, already reached maximum')
```

2022-12-27 04:18 UTC, baronkobama commented on pycord/ui/house.py
>  from ..undefined import UNDEFINED, UndefinedType
Reverts out of scope change.
```suggestion
from ..errors import ComponentException

from ..enums import ButtonStyle, SelectMenuType
from ..media import Emoji
from ..types import AsyncFunc
from ..undefined import UNDEFINED, UndefinedType
```

2022-12-31 08:27 UTC, VincentRPS commented on pycord/state/core.py
> +            t.append(self._process_global_command(app_command, command))
It is data, I just forgot to change the type hint when I renamed some stuff

2022-12-31 08:28 UTC, VincentRPS commented on pycord/state/core.py
> +    async def _process_global_command_for(self, command: Command) -> list[Coroutine]:
people could make their own application command class without subclassing app command itself.

2022-12-31 08:29 UTC, VincentRPS commented on pycord/state/core.py
> +            )
Can't do much about it. This isn't a styling PR.

2022-12-31 08:30 UTC, VincentRPS commented on pycord/state/core.py
> +            for app_cmd in guild_commands:
this mainly: checks if a command named like that already exists in this guild, and if so edits instead of creating, and deletes commands which the bot shouldn't have.

2022-12-31 08:32 UTC, VincentRPS commented on pycord/state/core.py
> +            return
what? the code below executes **if** created is False

2022-12-31 08:33 UTC, VincentRPS commented on pycord/state/core.py
> +                    command.id = app_cmd['id']
Commands only support singular guilds right now so it's not a problem

2022-12-31 17:32 UTC, EmreTech commented on pycord/state/core.py
> +            return
Oh nevermind. I read that as `if created`.

2022-12-31 17:33 UTC, EmreTech commented on pycord/state/core.py
> +            )
Yes you can? Just because it isn't a styling PR doesn't mean you can't style the code the PR adds.

2022-12-31 17:34 UTC, EmreTech commented on pycord/state/core.py
> +            for app_cmd in guild_commands:
It would be nice if the user could disable the behavior of deleting unknown application commands. Otherwise it would ruin bot setups where application commands are split between multiple different instances of the bot.

2022-12-31 17:36 UTC, EmreTech commented on pycord/state/core.py
> +    async def _process_global_command_for(self, command: Command) -> list[Coroutine]:
No they shouldn't? The subclass wouldn't be an application command, it would just be a janky normal command.

2022-12-31 17:52 UTC, VincentRPS commented on pycord/state/core.py
> +            )
Hard to do that without styling the other bits of the library

2022-12-31 17:57 UTC, EmreTech commented on pycord/state/core.py
> +            )
Then do it manually? Your formatting tools style according to PEP 8, so just open that up and read through the guidelines.

2022-12-31 18:19 UTC, EmreTech requested changes

2022-12-31 18:19 UTC, EmreTech commented on pycord/state/core.py
> +                self.id = res['id']
```suggestion
                command.id = res['id']
```

2022-12-31 18:19 UTC, EmreTech commented on pycord/state/core.py
> +            if self._created is True:
```suggestion
            if command._created is True:
```

2022-12-31 18:19 UTC, EmreTech commented on pycord/state/core.py
> +                await self.http.delete_global_application_command(
I'm confused. Why does this delete the global command and not recreate it? After calling this HTTP function, the method just returns.

2022-12-31 18:19 UTC, EmreTech commented on pycord/state/core.py
> +        if not created:
When is `created` ever `False` anyways? All of the pathways the code takes where `created` is still `False` all return prematurely without this code being ran.

2022-12-31 18:19 UTC, EmreTech commented on pycord/state/core.py
> +                if app_cmd['name'] not in self._application_command_names:
The attribute `_application_command_names` doesn't exist.

2023-02-22 13:39 UTC, VincentRPS commented on pycord/state/core.py
> +    async def _process_global_command_for(self, command: Command) -> list[Coroutine]:
> No they shouldn't? The subclass wouldn't be an application command, it would just be a janky normal command.

ApplicationCommand isn't a base class, so using it would mean having to do some jank stuff to override functions and everything. It would be much easier for the user to just sub class `Command` which is a base class

2023-02-22 13:40 UTC, VincentRPS commented on pycord/state/core.py
> +                    if created is True:
I didn't really choose to, my hands just decided to do that. I doubt it really matters much though.

2023-02-22 13:41 UTC, VincentRPS commented on pycord/state/core.py
> +            )
> Then do it manually? Your formatting tools style according to PEP 8, so just open that up and read through the guidelines.

I'm not gonna read the entirety of PEP 8 just for one PR about command syncing

2023-02-22 13:42 UTC, VincentRPS commented on pycord/state/core.py
> +            for app_cmd in guild_commands:
> It would be nice if the user could disable the behavior of deleting unknown application commands. Otherwise it would ruin bot setups where application commands are split between multiple different instances of the bot.

How? v3 supports that, and in any world this instance going up means that it's new and probably needs app commands globally refreshed.

2023-02-22 16:23 UTC, EmreTech commented on pycord/state/core.py
> +            for app_cmd in guild_commands:
> > It would be nice if the user could disable the behavior of deleting unknown application commands. Otherwise it would ruin bot setups where application commands are split between multiple different instances of the bot.
> 
> 
> 
> How? v3 supports that, and in any world this instance going up means that it's new and probably needs app commands globally refreshed.

Have you heard of booleans, the client, and the state? The client's initializer should have a parameter that can enable or disable deleting unknown application commands. Then pass that to the state and you're done. I don't see what the problem is?

2023-02-22 16:24 UTC, EmreTech commented on pycord/state/core.py
> +            )
You know you can run pre-commit on one file and only that file, right?

2023-02-22 16:26 UTC, EmreTech commented on pycord/state/core.py
> +                    if created is True:
Well, it's a PEP 8 guideline to not write code comparing a variable to a boolean. I doubt that matters to you because you don't seem to care about PEP 8 (see other discussion for proof).

2023-02-22 16:28 UTC, EmreTech commented on pycord/state/core.py
> +    async def _process_global_command_for(self, command: Command) -> list[Coroutine]:
From a logical perspective, it doesn't make sense. Whenever a user makes their own "custom application command" class, it's not going to even have the `ApplicationCommand` class as a parent. That means that the "custom application command" class isn't a custom application command class, it's a custom command class.

2023-02-22 22:04 UTC, VincentRPS commented on pycord/state/core.py
> +            )
I don't use pre-commit nor want to or plan to

2023-02-22 22:08 UTC, VincentRPS commented on pycord/state/core.py
> +    async def _process_global_command_for(self, command: Command) -> list[Coroutine]:
It doesn't need to be a custom application command, these just sync up commands which act like them

2023-02-22 22:09 UTC, VincentRPS commented on pycord/state/core.py
> +            for app_cmd in guild_commands:
No I wasn't asking how to do it, I was asking how it would ruin instance-based bot setups

2023-08-18 03:35 UTC, closed without merging