docs: add details on how to contribute
Pycord-Development/pycord-v3 pull request #114
Opened 2022-12-26 04:38 UTC by baronkobama

## Summary

This PR adds a CONTRIBUTING.md file with a guide on how to contribute, a bug report issue template, and improves the existing pull request template.

## Checklist

- [ ] This PR has breaking changes
- [ ] This PR fixes an issue
- [x] This is **not** a code change
- [ ] If code changes were made they have been tested
- [ ] I have properly changed the docs to appeal to this change

2022-12-26 04:51 UTC, EmreTech requested changes

2022-12-26 04:51 UTC, EmreTech commented on .github/CONTRIBUTING.md
> +1. If your issue produces a traceback/exception, include the entirety of it. Please put it in a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/
```suggestion
1. If your issue produces an exception, include the entire traceback in a [code block](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).
```
Exceptions always leave tracebacks, unless it's handled by another piece of code.

2022-12-26 04:51 UTC, EmreTech commented on .github/CONTRIBUTING.md
> +2. Fill out the template. If the template is not filled out properly, your issue will most likely be closed.
Isn't that what step 1 is telling you to do, but with the traceback only?

2022-12-26 04:51 UTC, EmreTech commented on .github/CONTRIBUTING.md
> +   1. Make sure your code is as clean as possible and looks similar to the rest of the codebase. This includes spacing, function signatures/definitions, and commenting/documentation format.
Encourage usage of pre-commit as well, since those hooks tackle formatting.

2022-12-26 04:51 UTC, EmreTech commented on .github/ISSUE_TEMPLATES/bug_report.yml
> +      description: Please provide the version/commit on which you are running the code on.
This sounds a little awkward, but I'm not sure what to change it to.

2022-12-26 04:51 UTC, EmreTech commented on .github/ISSUE_TEMPLATES/bug_report.yml
> +        - label: I have searched the currently open issues for duplicates.
```suggestion
        - label: I have searched all issues for duplicates.
```
The duplicate issue could also be closed.

2022-12-26 04:51 UTC, EmreTech commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] This PR improves the code (speed/style improvements or refactoring).
Style improvements would fall under "no code changes" because the styling isn't supposed to change the logic of the code.

2022-12-26 04:51 UTC, EmreTech commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] I have searched the currently open pull requests for duplicates.
```suggestion
- [ ] I have searched all pull requests for duplicates.
```

2022-12-26 04:51 UTC, EmreTech commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] I have tested the changes made (and they work).
```suggestion
- [ ] I have tested the changes made.
```
If it doesn't work, then why would the PR be opened?

2022-12-26 05:01 UTC, baronkobama commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] This PR improves the code (speed/style improvements or refactoring).
I'd like to be somewhat detailed with this part as "no code changes" would be a bit misleading, even if it doesn't change the logic behind the code.

2022-12-26 05:02 UTC, baronkobama commented on .github/ISSUE_TEMPLATES/bug_report.yml
> +      description: Please provide the version/commit on which you are running the code on.
We could just trim it to "version" instead of "version/commit"?

2022-12-26 05:04 UTC, baronkobama commented on .github/CONTRIBUTING.md
> +2. Fill out the template. If the template is not filled out properly, your issue will most likely be closed.
Somewhat, but the directions on how to make a code block should probably be put somewhere.

2022-12-26 05:52 UTC, baronkobama commented on .github/CONTRIBUTING.md
> +   1. Make sure your code is as clean as possible and looks similar to the rest of the codebase. This includes spacing, function signatures/definitions, and commenting/documentation format.
Not sure how that would look tbh with you, mind writing an example?

2022-12-27 03:29 UTC, VincentRPS approved these changes

2022-12-27 16:42 UTC, EmreTech requested changes
Add a feature request issue template and a section on writing a feature request.

2022-12-28 03:36 UTC, EmreTech requested changes

2022-12-28 03:36 UTC, EmreTech commented on .github/ISSUE_TEMPLATES/feature_request.yml
> +        What is the general purpose of this PR? What exactly becomes easier or
```suggestion
        What is the general purpose of this feature request? What exactly becomes easier or 
```

2022-12-28 04:59 UTC, EmreTech approved these changes

2022-12-28 08:44 UTC, merged