refactor: conform to pyright strict
Pycord-Development/pycord-v3 pull request #144
Opened 2023-02-14 10:36 UTC by VincentRPS

## Summary

Conforms the repository code for Pyright strict.

Supersedes #84

## PR Type

- [x] This PR improves the code (speed/style improvements or refactoring).
- [ ] This PR fixes an issue.
- [ ] This PR makes an addition to the library (new file, class, method, parameters, etc.).
- [ ] This PR makes a breaking change (renaming/removing parameters, methods, etc.).
- [ ] This PR doesn't make any code changes to the library (documentation, examples).

## Checklist

- [ ] I have searched all pull requests for duplicates.
- [ ] I have tested the changes made.
  - [ ] I have properly changed the docs to reflect the changes made.
- [ ] If 'type: ignore' comments were used, a comment is left to explain why it is needed.

2023-02-14 23:04 UTC, EmreTech requested changes
A lot of the typing problems have been fixed by slapping on a `type: ignore` comment. This is hardly conforming to Pyright Strict.

2023-02-14 23:04 UTC, EmreTech commented on pycord/api/route.py
> -        pass
How is using `...` instead of `pass` a Pyright Strict related change?

2023-02-14 23:44 UTC, VincentRPS commented
> A lot of the typing problems have been fixed by slapping on a `type: ignore` comment. This is hardly conforming to Pyright Strict.

Much of the errors are because of accessing private values on another class, of which I do not care about

2023-02-14 23:45 UTC, VincentRPS commented on pycord/api/route.py
> -        pass
It tells pyright it's a base class or something like that, because with `pass` it "returns" none but with `...` it's based

2023-02-15 00:48 UTC, EmreTech commented
> > A lot of the typing problems have been fixed by slapping on a `type: ignore` comment. This is hardly conforming to Pyright Strict.
> 
> Much of the errors are because of accessing private values on another class, of which I do not care about

Then disable reports of private members being accessed?

2023-02-24 11:50 UTC, closed without merging